### ISSUE TITLE
Lan tap only works when monitor port is connected

### ISSUE THREAD

**Issue by mrockey19** [greatscottgadgets/throwing-star-lan-tap#1]
Hi,

I wanted to know if it was normal operation for the tap to only pass traffic on the J1 and J2 ports when one of the monitor ports is connected? For example, when a switch is connected to J1, and a computer to J2, the computer on J2 will show "No LAN cable connected" until a monitoring device is connected to J3. 

Thanks,
Michael

**Comment by mossmann** [comment]
No, that is not expected.  Do you have a cable plugged in to one or both of the monitor ports?  A dangling cable without a connection to a monitoring host can introduce a reflection that could result in a loss of communication.  This kind of problem is more likely when there are longer cables connected on J1 and/or J2.

**Comment by mrockey19** [comment]
I think that was the issue. I was monitoring with a 25ft cable connected to 1 of the monitor ports. I was disconnecting the monitor host but not the monitor patch cable.

After your message I tried connecting J1 and J2 with no cable on the monitoring ports and it worked fine. 

Thanks for the quick and helpful response.
