### ISSUE TITLE
Lan tap switches off when two interfaces connected

### ISSUE THREAD

**Issue by ricamz** [greatscottgadgets/throwing-star-lan-tap#11]
Hi there.

I have a throwing star lan tap pro, already assembled.

When I connect the two monitoring interfaces (J3 and J4) to any device (even separate devices) , the network ports where the monitoring interfaces are connected switches off, although the traffic apparently continues to pass through. Why does that happen?

The clarify I will do a step by step:

1. connect the throwing star lan tap pro pass through interfaces J1 and J2 in the network and everything works fine.
2. connect one monitoring interface (J3 or J4) to switch and i can sniff traffic only in one direction
3. connect the other monitoring interface to different computer and both monitoring interfaces switch off

Now I just have one monitoring interface connected.

What could be the reason of this and how can I solve it? Is it a faulty lan tap?

Regards

RS

**Comment by straithe** [comment]
Can you please provide a picture of your set up? That would really help in diagnosing your issue.

**Comment by ricamz** [comment]
![throwingstar drawio](https://github.com/greatscottgadgets/throwing-star-lan-tap/assets/34093136/e710f108-dd12-429e-8362-3888424e2fdc)

Above is the drawing. When I connect the red line (from J4 to the switch) the throwing star J3 and J4 switches off. J1 and J2 continues to operate.

The purple icon is the Lan tap.

I even tried to connect the J3 and J4 to different switches (due to possible spanning tree of the switch) but same behaviour.

**Comment by mossmann** [comment]
It is unusual to connect the monitor ports to a switch. I would expect that to work only with certain switch models and only when their ports are configured for promiscuous mirroring.

Does this happen if you connect J3 and J4 to promiscuous-mode host ports instead of to a switch?

**Comment by ricamz** [comment]
Hi Mossmann.

I didn't connect J3 and J4 to a promiscuous-mode host ports. What I did is connect J3 to a switch and J4 to a promiscuous-mode host ports and the behaviour was J3 and J4 went shutdown.

By connecting J3 and J4 to a promiscuous-mode host ports you would need two network interfaces in the host, and I don't have that. I just have one network interface left.

Didn't you use old network hubs to connect J3 and J4?

Ricardo

**Comment by mossmann** [comment]
You could connect J3 and J4 to hubs, but connecting them to the same hub would result in a high probability of collision if there is full-duplex traffic on J1/J2. Collisions on a J3/J4 hub would not affect the J1/J2 network, but they would cause the monitoring station to miss packets randomly. It would be a good test, though; even if you miss some packets due to collision, you should still be able to confirm that you can monitor packets in both directions.

**Comment by ricamz** [comment]
I don't have hubs to try. 

I have tried to connect J3 and J4 to different switches and both ports shutdown once I do this. Even with ports with no port security configured, they still shutdown.

I also have tried to connect J3 to a switch and J4 to host promiscuous mode port in a host and they both shutdown.

Do you think it is my lan tap has some defect and I should get another one or it is some problem of my setup?

Thanks for the help in advance.

Ricardo

**Comment by mossmann** [comment]
TSLT is a passive tap. Ports J3 and J4 are wired directly to J1 and J2. There is no way for a TSLT to shut down or switch off a port. If you are seeing traffic stop completely on J3 or J4, it is likely because of behavior of the device connected to the port, not because of any behavior of the TSLT.

**Comment by mossmann** [comment]
I do not think there is anything wrong with your TSLT. I recommend connecting both J3 and J4 to two promiscuous-mode host ports. The two ports need not be on the same host.

**Comment by ricamz** [comment]
Thank you for the explanation. It is strange what is happening, but I will try connecting to two host ports to see what happens. If the issue continues, I will re-open this thread.

But the strangest thing was that if I connect on a switch and to a host port (in promisc.) both J3 and J4 switch off.

**Comment by mossmann** [comment]
I agree that is strange. Are you certain that J1 and J2 are operating normally with successful communication in both directions when traffic stops on J3 and J4?

**Comment by ricamz** [comment]
I think so, because it is a firewall that serves many requests and if it fails for a bit I would have some complain and I didn't had any. But I haven't done any test to be sure.

Furthermore, if I disconnect J3 and J4, wait a bit and connect J3 alone (or J4 alone) I can monitor the traffic in one direction.
