### ISSUE TITLE
Throwing Star Mirror Port Mappings

### ISSUE THREAD

**Issue by KarelVenter** [greatscottgadgets/throwing-star-lan-tap#2]
Hi guys

I recently bought a Throwing Star Pro and need to understand which mirror ports maps to which source ports. Maybe I missed something but I cannot find this info on the website?

My assumption:
J3 = Tx feed from J1
J4 = Tx feed from J2

Would you please confirm?

Many thanks

**Comment by DRIgnazGortngschirl** [comment]
Hope you figured it out already but for all others who are searching for the info. 

# Usage

 1. Use Ethernet cables to connect the Throwing Star LAN Tap (J1 and J2) in line with a target network to be monitored.
2. Use Ethernet cables to connect one or both of the monitoring ports (J3 and J4) to ports on one or two monitoring stations. Each port monitors traffic in one direction only.
3. Use your favorite software (e.g., tcpdump or Wireshark) on the monitoring station(s) to capture network traffic.

http://greatscottgadgets.com/throwingstar/

**Comment by mburr-precor** [comment]
According to the attached schematic (which was harder to find than I expected):

  - data transmitted by the J1 device shows up on J3
  - data transmitted by the J2 device shows up on J4

[throwing.star.lan.tap.schematic.pdf](https://github.com/greatscottgadgets/throwing-star-lan-tap/files/5009474/throwing.star.lan.tap.schematic.pdf)

**Comment by KarelVenter** [comment]
Haha! This could not have been easy, it's literally been almost a year since my original query. Many many thanks. So, easy way to remember is that odd nr map to odd (J1 to J3) and even to even (J2 to J4).
