### ISSUE TITLE
Link LEDs should light up on target network ?

### ISSUE THREAD

**Issue by honza-1** [greatscottgadgets/throwing-star-lan-tap#3]
Hi,

I cannot make my LAN Tap Pro work. Additionally I would expect, when I connect a computer on J1 and a switch on J2 both on the target network, that on both sides the Link LEDs should light up/blink. Am I wrong. Is my Lan Tap damaged ?

Thankks fo advise.

Honza

**Comment by miek** [comment]
The link LEDs should light on both ends (the same as if a single cable were connected between them).

It's worth making sure that both ends support 100BASETX and 10BASET as the LAN Tap will intentionally degrade the connection and force the link to be negotiated at a slower speed than usual. This may also change the behaviour of the link LEDs.

Also, make absolutely sure that the cables that you're testing with are good - ideally try some other ones in different combinations.

**Comment by mossmann** [comment]
Are you still having trouble?  We will close this ticket in a month if we don't see a response.

**Comment by straithe** [comment]
I'm going to close this as there hasn't been a response in a while, but please re-open this issue or open a new one if you still need assistance.
