### ISSUE TITLE
No carrier on bottom tap link

### ISSUE THREAD

**Issue by rogerjames99** [greatscottgadgets/throwing-star-lan-tap#6]
I have had a Throwing Star lan tap for a number of years now but have not used it for some time. I have two rtl8169 pci ethernet adapters connected to the two. No matter what combination of cables and adapters I use I cannot get any carrier detected on the lower tap  interface (viewed with the legend "Throwing Star Lan Tap" on the pcb the the right way up). I have also tried this with a recently purchased Pro version with the same results. Do you have any ideas on what may be causing this? Have you had any reports of rtl8169 based adaptors causing problems. Could this be anything to do with MDI-X.

**Comment by miek** [comment]
If you swap the left and right connections, does the problem stay on the bottom tap or move to the top?

**Comment by rogerjames99** [comment]
Stays on the bottom.

Also tested the the lower tap with a usb adapter based on the  rtl8153 chip. Same result. I remember that some time ago I go the original tap working on a different piece of kit by using a pair of crossover cables one for each tap.

I am really scratching my head on this one. This isnt anything in these things to go wrong.

I have just noticed that the carrier goes off on the through link when the bottom cable is plugged in. I will find or make some nice short cables and see what happens.

**Comment by mossmann** [comment]
I think you could be right about it being related to MDI/MDI-X. Here are some things you could try: Use the shortest cables you can (especially on the monitor ports). Try a crossover cable only on the failing port. Manually set all monitoring and target interfaces to 100BASE-TX.

**Comment by straithe** [comment]
I'm going to close this as is looks like this issue has been solved. Please re-open this issue or open a new one if you still need assistance.
