### ISSUE TITLE
No packets on router

### ISSUE THREAD

**Issue by thorag76** [greatscottgadgets/throwing-star-lan-tap#7]
I am able to capture packets on the LAN this works perfectly. But I was also hoping to be able to capture packets on the DSL interface of a Fritz!Box, which is a WAN port. With the device looped in the DSL connection, the connection can still be established successfully but I don't see any packets on either of the side jacks. The DSL RJ45 plug only  has 2 wires (the ones in the  middle).

**Comment by mossmann** [comment]
Throwing Star LAN Tap was definitely not designed for DSL, but there is some potential that you could figure out a way to do what you want. The middle two wires (pins 4 and 5) on connectors J1 and J2 connect to pins 7 and 8 on connector J3. They do not connect to J4. If you were to crimp your own cable, you could connect this pair on J3 to a monitoring device. I have no idea if any DSL devices support a monitoring mode, but maybe this will get you started!

**Comment by straithe** [comment]
I'm going to close this as it looks like this issue has been solved. Please re-open this issue or open a new one if you still need assistance.
